//! Editor integration for Vim/Neovim and VS Code.
//!
//! Generates plugins and provides integration info for popular editors.

/// Generate a Vim/Neovim plugin.
///
/// Returns the plugin script that can be saved to ~/.vim/plugin/clings.vim
/// or ~/.config/nvim/plugin/clings.vim
pub fn generate_vim_plugin() -> String {
    r#"" clings.vim - Things 3 integration for Vim/Neovim
" Generated by: clings shell editor vim
"
" Installation:
"   Save to ~/.vim/plugin/clings.vim (Vim)
"   Save to ~/.config/nvim/plugin/clings.vim (Neovim)
"
" Commands:
"   :ClingsInbox      - Show inbox items
"   :ClingsToday      - Show today's items
"   :ClingsAdd <text> - Quick add a todo
"   :ClingsPick       - Interactive picker (requires fzf)
"   :ClingsSearch     - Search todos
"
" Mappings (customize in your vimrc):
"   <leader>ci - Show inbox
"   <leader>ct - Show today
"   <leader>ca - Quick add (prompts for text)
"   <leader>cp - Interactive picker

if exists('g:loaded_clings')
  finish
endif
let g:loaded_clings = 1

" Configuration
let g:clings_executable = get(g:, 'clings_executable', 'clings')
let g:clings_output_format = get(g:, 'clings_output_format', 'pretty')

" Helper function to run clings commands
function! s:ClingRun(cmd) abort
  let l:output = system(g:clings_executable . ' ' . a:cmd)
  if v:shell_error
    echohl ErrorMsg
    echo 'clings error: ' . l:output
    echohl None
    return ''
  endif
  return l:output
endfunction

" Show output in a scratch buffer
function! s:ShowInBuffer(title, content) abort
  " Create or reuse clings buffer
  let l:bufname = '[clings]'
  let l:bufnr = bufnr(l:bufname)

  if l:bufnr == -1
    execute 'new ' . l:bufname
    setlocal buftype=nofile
    setlocal bufhidden=wipe
    setlocal noswapfile
    setlocal nowrap
    setlocal filetype=clings
  else
    let l:winnr = bufwinnr(l:bufnr)
    if l:winnr == -1
      execute 'sbuffer ' . l:bufnr
    else
      execute l:winnr . 'wincmd w'
    endif
  endif

  " Clear and fill buffer
  setlocal modifiable
  silent %delete _
  call setline(1, split(a:content, "\n"))
  setlocal nomodifiable

  " Set window title
  let &l:statusline = ' clings: ' . a:title
endfunction

" Commands
command! ClingsInbox call s:ShowInBuffer('Inbox', s:ClingRun('inbox'))
command! ClingsToday call s:ShowInBuffer('Today', s:ClingRun('today'))
command! ClingsUpcoming call s:ShowInBuffer('Upcoming', s:ClingRun('upcoming'))
command! ClingsAnytime call s:ShowInBuffer('Anytime', s:ClingRun('anytime'))
command! ClingsSomeday call s:ShowInBuffer('Someday', s:ClingRun('someday'))
command! ClingsLogbook call s:ShowInBuffer('Logbook', s:ClingRun('logbook'))
command! ClingsProjects call s:ShowInBuffer('Projects', s:ClingRun('project list'))
command! ClingsTags call s:ShowInBuffer('Tags', s:ClingRun('tags'))
command! ClingsAreas call s:ShowInBuffer('Areas', s:ClingRun('areas'))

" Add todo with argument
command! -nargs=+ ClingsAdd echo s:ClingRun('add "' . <q-args> . '"')

" Search with argument
command! -nargs=+ ClingsSearch call s:ShowInBuffer('Search', s:ClingRun('search "' . <q-args> . '"'))

" Filter with expression
command! -nargs=+ ClingsFilter call s:ShowInBuffer('Filter', s:ClingRun('filter "' . <q-args> . '"'))

" Interactive picker (requires terminal support)
command! ClingsPick call s:RunPicker()

function! s:RunPicker() abort
  if has('nvim')
    " Neovim terminal
    new
    call termopen(g:clings_executable . ' pick', {'on_exit': function('s:OnPickerExit')})
    startinsert
  elseif has('terminal')
    " Vim 8+ terminal
    call term_start(g:clings_executable . ' pick', {'term_finish': 'close'})
  else
    echo 'Terminal support required for picker'
  endif
endfunction

function! s:OnPickerExit(job_id, code, event) abort
  if a:code == 0
    close
  endif
endfunction

" Quick add with prompt
function! s:QuickAdd() abort
  let l:text = input('Add todo: ')
  if !empty(l:text)
    echo "\n" . s:ClingRun('add "' . l:text . '"')
  endif
endfunction
command! ClingsQuickAdd call s:QuickAdd()

" Add todo from current line (useful for TODO comments)
function! s:AddFromLine() abort
  let l:line = getline('.')
  " Extract TODO/FIXME content
  let l:match = matchstr(l:line, '\v(TODO|FIXME|XXX|HACK):\s*\zs.*')
  if empty(l:match)
    let l:match = l:line
  endif
  let l:match = substitute(l:match, '^\s*\(//\|#\|"\|--\)\s*', '', '')
  if !empty(l:match)
    echo s:ClingRun('add "' . l:match . '"')
  else
    echo 'No todo content found on current line'
  endif
endfunction
command! ClingsAddLine call s:AddFromLine()

" Default mappings (can be disabled with g:clings_no_mappings)
if !exists('g:clings_no_mappings')
  nnoremap <leader>ci :ClingsInbox<CR>
  nnoremap <leader>ct :ClingsToday<CR>
  nnoremap <leader>ca :ClingsQuickAdd<CR>
  nnoremap <leader>cp :ClingsPick<CR>
  nnoremap <leader>cl :ClingsAddLine<CR>
endif

" Syntax highlighting for clings buffer
augroup clings_syntax
  autocmd!
  autocmd FileType clings call s:SetupSyntax()
augroup END

function! s:SetupSyntax() abort
  syntax match clingsCompleted /\[x\].*$/
  syntax match clingsPending /\[ \].*$/
  syntax match clingsTag /#\w\+/
  syntax match clingsDate /\d\{4}-\d\{2}-\d\{2}/
  syntax match clingsProject /for \w\+/
  syntax match clingsHeader /^.*:$/

  highlight link clingsCompleted Comment
  highlight link clingsPending Normal
  highlight link clingsTag Identifier
  highlight link clingsDate Number
  highlight link clingsProject Type
  highlight link clingsHeader Title
endfunction
"#.to_string()
}

/// Get VS Code extension information.
pub fn vscode_info() -> String {
    r#"VS Code Integration for clings

There is no official VS Code extension yet, but you can integrate clings
using VS Code tasks and keybindings.

1. Add to .vscode/tasks.json:
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "clings: Today",
      "type": "shell",
      "command": "clings today",
      "presentation": {
        "reveal": "always",
        "panel": "dedicated"
      }
    },
    {
      "label": "clings: Add Todo",
      "type": "shell",
      "command": "clings add \"${input:todoText}\"",
      "presentation": {
        "reveal": "always"
      }
    },
    {
      "label": "clings: Pick",
      "type": "shell",
      "command": "clings pick",
      "presentation": {
        "reveal": "always",
        "panel": "dedicated",
        "focus": true
      },
      "runOptions": {
        "instanceLimit": 1
      }
    }
  ],
  "inputs": [
    {
      "id": "todoText",
      "type": "promptString",
      "description": "Todo text (natural language)"
    }
  ]
}

2. Add keybindings to keybindings.json:
[
  {
    "key": "ctrl+shift+t",
    "command": "workbench.action.tasks.runTask",
    "args": "clings: Today"
  },
  {
    "key": "ctrl+shift+a",
    "command": "workbench.action.tasks.runTask",
    "args": "clings: Add Todo"
  },
  {
    "key": "ctrl+shift+p",
    "command": "workbench.action.tasks.runTask",
    "args": "clings: Pick"
  }
]

3. Recommended Extensions:
   - "Task Explorer" - browse and run tasks from sidebar
   - "Terminal" - better terminal integration

For more information, see: https://code.visualstudio.com/docs/editor/tasks
"#.to_string()
}

/// Generate Emacs integration.
pub fn generate_emacs_config() -> String {
    r#";; clings.el - Things 3 integration for Emacs
;; Generated by: clings shell editor emacs
;;
;; Add to your init.el or .emacs:
;;   (load "/path/to/clings.el")
;;
;; Commands:
;;   M-x clings-inbox      - Show inbox
;;   M-x clings-today      - Show today
;;   M-x clings-add        - Quick add
;;   M-x clings-pick       - Interactive picker

(defgroup clings nil
  "Things 3 CLI integration."
  :group 'tools)

(defcustom clings-executable "clings"
  "Path to clings executable."
  :type 'string
  :group 'clings)

(defun clings--run (args)
  "Run clings with ARGS and return output."
  (shell-command-to-string (concat clings-executable " " args)))

(defun clings--show-buffer (name content)
  "Show CONTENT in a buffer named NAME."
  (with-current-buffer (get-buffer-create (format "*clings: %s*" name))
    (setq buffer-read-only nil)
    (erase-buffer)
    (insert content)
    (setq buffer-read-only t)
    (clings-mode)
    (pop-to-buffer (current-buffer))))

(defun clings-inbox ()
  "Show inbox todos."
  (interactive)
  (clings--show-buffer "Inbox" (clings--run "inbox")))

(defun clings-today ()
  "Show today's todos."
  (interactive)
  (clings--show-buffer "Today" (clings--run "today")))

(defun clings-upcoming ()
  "Show upcoming todos."
  (interactive)
  (clings--show-buffer "Upcoming" (clings--run "upcoming")))

(defun clings-add (text)
  "Add a todo with TEXT."
  (interactive "sAdd todo: ")
  (message "%s" (clings--run (format "add \"%s\"" text))))

(defun clings-search (query)
  "Search todos for QUERY."
  (interactive "sSearch: ")
  (clings--show-buffer "Search" (clings--run (format "search \"%s\"" query))))

(defun clings-pick ()
  "Open interactive picker."
  (interactive)
  (let ((default-directory "~"))
    (term (concat clings-executable " pick"))))

;; Major mode for clings buffers
(define-derived-mode clings-mode special-mode "Clings"
  "Major mode for viewing clings output."
  (setq-local truncate-lines t))

;; Keybindings
(global-set-key (kbd "C-c t i") 'clings-inbox)
(global-set-key (kbd "C-c t t") 'clings-today)
(global-set-key (kbd "C-c t a") 'clings-add)
(global-set-key (kbd "C-c t s") 'clings-search)
(global-set-key (kbd "C-c t p") 'clings-pick)

(provide 'clings)
;; clings.el ends here
"#.to_string()
}

/// Get Sublime Text integration info.
pub fn sublime_info() -> String {
    r#"Sublime Text Integration for clings

Add to your User packages (Preferences > Browse Packages > User):

1. Create clings.sublime-build:
{
    "shell_cmd": "clings ${file_base_name}",
    "selector": "source",
    "variants": [
        {
            "name": "Today",
            "shell_cmd": "clings today"
        },
        {
            "name": "Inbox",
            "shell_cmd": "clings inbox"
        },
        {
            "name": "Add",
            "shell_cmd": "clings add \"$selection\""
        }
    ]
}

2. Add keybindings to Default (OSX).sublime-keymap:
[
    { "keys": ["super+shift+t"], "command": "build", "args": {"variant": "Today"} },
    { "keys": ["super+shift+i"], "command": "build", "args": {"variant": "Inbox"} }
]
"#.to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_vim_plugin_contains_commands() {
        let plugin = generate_vim_plugin();
        assert!(plugin.contains("ClingsInbox"));
        assert!(plugin.contains("ClingsToday"));
        assert!(plugin.contains("ClingsAdd"));
        assert!(plugin.contains("ClingsPick"));
    }

    #[test]
    fn test_vscode_info_contains_tasks() {
        let info = vscode_info();
        assert!(info.contains("tasks.json"));
        assert!(info.contains("keybindings"));
    }

    #[test]
    fn test_emacs_config_contains_functions() {
        let config = generate_emacs_config();
        assert!(config.contains("clings-inbox"));
        assert!(config.contains("clings-today"));
        assert!(config.contains("clings-add"));
    }
}
